In [41]:
import pickle
import pandas as pd
import numpy as np

In [60]:
with open('./total_results2.pickle', mode='rb') as f:
    tot_results = pickle.load(f)
with open('./study.pickle', mode='rb') as f:
    study = pickle.load(f)

In [61]:
result_df = pd.DataFrame(tot_results)
result_df

,originaldeepfm,sparseSVDfm,sparseNMFfm,NMFdeepfm,originalfm
precision,"[0.036238532110091745, 0.06743119266055045, 0....","[0.06284403669724771, 0.04724770642201835]","[0.06743119266055046, 0.08440366972477063, 0.0...",[0.04724770642201835],[0.031192660550458717]
recall,"[0.003753574703071431, 0.007963861200318945, 0...","[0.005712401276157996, 0.006042005671180915]","[0.009443837388004068, 0.010176266180260185, 0...",[0.003108565993188725],[0.00298771017514286]
hit_rate,"[0.16055045871559634, 0.2591743119266055, 0.20...","[0.231651376146789, 0.2018348623853211]","[0.2545871559633027, 0.30504587155963303, 0.33...",[0.17660550458715596],[0.13302752293577982]
reciprocal_rank,"[0.05577217125382263, 0.11498470948012234, 0.1...","[0.13562691131498472, 0.10504587155963302]","[0.14533639143730887, 0.12033639143730886, 0.1...",[0.07354740061162078],[0.060435779816513754]
dcg,"[0.08953779591715816, 0.18445454103571443, 0.1...","[0.19894050610312558, 0.14487988095562038]","[0.21196428696844935, 0.21871987541723031, 0.2...",[0.12480045216736971],[0.08840870831490995]
threshold,NaN,"[0.09664857057225569, 0.08486737032359866]","[0.0912814854109767, 0.05552385536995787, 0.05...",NaN,NaN

In [62]:
result_df.map(lambda x: np.mean(x))

,originaldeepfm,sparseSVDfm,sparseNMFfm,NMFdeepfm,originalfm
precision,0.053058,0.055046,0.079817,0.047248,0.031193
recall,0.005766,0.005877,0.009745,0.003109,0.002988
hit_rate,0.209480,0.216743,0.298930,0.176606,0.133028
reciprocal_rank,0.100127,0.120336,0.147146,0.073547,0.060436
dcg,0.151975,0.171910,0.231001,0.124800,0.088409
threshold,NaN,0.090758,0.066928,NaN,NaN