In [1]:
import pickle
import pandas as pd
import numpy as np
import optuna
import plotly

In [3]:
with open('./total_results2.pickle', mode='rb') as f:
    tot_results = pickle.load(f)
with open('./study.pickle', mode='rb') as f:
    study = pickle.load(f)

In [4]:
result_df = pd.DataFrame(tot_results)
result_df

,originalfm,NMFfm,sparseNMFdeepfm,sparseNMFfm,originaldeepfm,sparseSVDdeepfm,SVDfm,NMFdeepfm,SVDdeepfm,sparseSVDfm
precision,[0.41284403669724784],"[0.2830275229357798, 0.2651376146788991, 0.266...","[0.5018348623853212, 0.5059633027522936, 0.501...","[0.24449541284403672, 0.26422018348623855, 0.2...","[0.45458715596330274, 0.434862385321101, 0.443...","[0.43853211009174314, 0.5142201834862385, 0.50...","[0.13853211009174313, 0.1834862385321101, 0.15...","[0.48440366972477067, 0.5334862385321102, 0.54...","[0.5279816513761468, 0.531651376146789, 0.4899...",[0.12660550458715597]
recall,[0.06794906013796619],"[0.0427589035527344, 0.0349265164653582, 0.033...","[0.0890222690231811, 0.08933464018305351, 0.08...","[0.03162106172004985, 0.032502171521704204, 0....","[0.08313535188674191, 0.07532724009780147, 0.0...","[0.08579011905450655, 0.09732540028790604, 0.0...","[0.024404794873923063, 0.022448622456900567, 0...","[0.08788579922596876, 0.0951046219543885, 0.09...","[0.0987134719035328, 0.09529663197651747, 0.08...",[0.01814920541334643]
hit_rate,[0.8440366972477065],"[0.7064220183486238, 0.6215596330275229, 0.607...","[0.8922018348623854, 0.9128440366972477, 0.887...","[0.6146788990825688, 0.5779816513761468, 0.610...","[0.8623853211009175, 0.8463302752293578, 0.846...","[0.8761467889908257, 0.9197247706422018, 0.908...","[0.5045871559633027, 0.5068807339449541, 0.488...","[0.9059633027522935, 0.9013761467889908, 0.917...","[0.9059633027522935, 0.9128440366972477, 0.912...",[0.4380733944954128]
reciprocal_rank,[0.5474770642201835],"[0.5073394495412844, 0.48233944954128444, 0.45...","[0.7053899082568806, 0.6928134556574923, 0.684...","[0.4705657492354739, 0.4435015290519878, 0.455...","[0.6492354740061163, 0.628019877675841, 0.6048...","[0.6410550458715596, 0.7062691131498471, 0.724...","[0.22373853211009176, 0.31957186544342503, 0.2...","[0.6622324159021407, 0.7332568807339449, 0.723...","[0.7339449541284404, 0.7459097859327216, 0.710...",[0.25535168195718655]
dcg,[1.200861424439266],"[0.907651186233312, 0.865308494321722, 0.84898...","[1.526604071255968, 1.5291046657064746, 1.5102...","[0.8092652440717891, 0.8402596209124079, 0.828...","[1.3793862236527001, 1.3208262253205056, 1.313...","[1.3230862375313082, 1.5533442118263754, 1.539...","[0.3776244620829442, 0.5669137448242832, 0.464...","[1.453276415564982, 1.632371376629842, 1.63117...","[1.6122571276822417, 1.6325096505060475, 1.497...",[0.39255238029266015]
threshold,NaN,NaN,"[0.0394969692281849, 0.007623079433767409, 0.0...","[0.06651813086746282, 0.05343493517313639, 0.0...",NaN,"[0.07006388365852562, 0.030768915207078227, 0....",NaN,NaN,NaN,[0.04012568938183006]

In [5]:
mean_result_df = result_df.map(lambda x: np.mean(x))
mean_result_df

,originalfm,NMFfm,sparseNMFdeepfm,sparseNMFfm,originaldeepfm,sparseSVDdeepfm,SVDfm,NMFdeepfm,SVDdeepfm,sparseSVDfm
precision,0.412844,0.264106,0.497706,0.255505,0.449032,0.479493,0.148853,0.507711,0.508419,0.126606
recall,0.067949,0.035804,0.088373,0.032720,0.081232,0.088999,0.022256,0.090759,0.091981,0.018149
hit_rate,0.844037,0.637041,0.895592,0.600917,0.862895,0.889234,0.476491,0.901485,0.911090,0.438073
reciprocal_rank,0.547477,0.475841,0.700444,0.456562,0.656503,0.684030,0.243645,0.712697,0.714061,0.255352
dcg,1.200861,0.852411,1.517069,0.826095,1.371924,1.459853,0.424879,1.550011,1.548506,0.392552
threshold,NaN,NaN,0.041974,0.055005,NaN,0.035882,NaN,NaN,NaN,0.040126

In [6]:
mean_result_df[['originalfm', 'originaldeepfm', 'SVDfm', 'sparseSVDfm', 'SVDdeepfm', 'sparseSVDdeepfm', 'NMFfm', 'sparseNMFfm', 'NMFdeepfm', 'sparseNMFdeepfm',]]

,originalfm,originaldeepfm,SVDfm,sparseSVDfm,SVDdeepfm,sparseSVDdeepfm,NMFfm,sparseNMFfm,NMFdeepfm,sparseNMFdeepfm
precision,0.412844,0.449032,0.148853,0.126606,0.508419,0.479493,0.264106,0.255505,0.507711,0.497706
recall,0.067949,0.081232,0.022256,0.018149,0.091981,0.088999,0.035804,0.032720,0.090759,0.088373
hit_rate,0.844037,0.862895,0.476491,0.438073,0.911090,0.889234,0.637041,0.600917,0.901485,0.895592
reciprocal_rank,0.547477,0.656503,0.243645,0.255352,0.714061,0.684030,0.475841,0.456562,0.712697,0.700444
dcg,1.200861,1.371924,0.424879,0.392552,1.548506,1.459853,0.852411,0.826095,1.550011,1.517069
threshold,NaN,NaN,NaN,0.040126,NaN,0.035882,NaN,0.055005,NaN,0.041974

In [7]:
from optuna.visualization import plot_optimization_history, plot_param_importances

In [11]:
with open('./study2.pickle', mode='wb') as f:
    pickle.dump(study, f)